import {
  Activity,
  AlertTriangle,
  Award,
  Bell,
  ClipboardCheck,
  FileText,
  Flag,
  Gauge,
  Gift,
  Home,
  ListChecks,
  Medal,
  PlusCircle,
  ShieldCheck,
  Siren,
  Star,
  Trophy,
  Users,
  Wallet,
} from "lucide-react";

import type { NavigationItem } from "@/types/navigation";

export const publicNavigation: NavigationItem[] = [
  { title: "Home", href: "/", icon: Home },
  { title: "Tournaments", href: "/tournaments", icon: Trophy },
  { title: "Races", href: "/races", icon: Flag },
  { title: "Rankings", href: "#", icon: Gauge },
  { title: "Predictions", href: "#", icon: Bell },
  { title: "News", href: "#", icon: ClipboardCheck },
  { title: "Contact", href: "/#contact", icon: Users },
];

export const dashboardNavigation: NavigationItem[] = [
  // ─── ADMIN ──────────────────────────────────────────────────────────
  {
    title: "Admin Dashboard",
    href: "/admin",
    role: "Admin",
    icon: Gauge,
    description: "Tổng quan hệ thống: users, tournaments, races, bets.",
  },
  {
    title: "Quản Lý & Phân Quyền",
    href: "/admin/users",
    role: "Admin",
    icon: Users,
    description: "Quản lý tài khoản: xem, ban/unban, xóa và phân quyền hệ thống.",
  },
  {
    title: "Horse Management",
    href: "/admin/horses",
    role: "Admin",
    icon: ShieldCheck,
    description: "Quản lý ngựa: xem toàn bộ, cập nhật trạng thái.",
  },
  {
    title: "Jockey Management",
    href: "/admin/jockeys",
    role: "Admin",
    icon: Star,
    description: "Quản lý jockey: duyệt profiles, đổi trạng thái.",
  },
  {
    title: "Tournament Management",
    href: "/admin/tournaments",
    role: "Admin",
    icon: Trophy,
    description: "Quản lý giải: tạo, cập nhật, thay đổi trạng thái.",
  },
  {
    title: "Registration Approval",
    href: "/admin/registrations",
    role: "Admin",
    icon: ClipboardCheck,
    description: "Duyệt đăng ký: approve/reject horse registrations.",
  },
  {
    title: "Race Scheduling",
    href: "/admin/races",
    role: "Admin",
    icon: Flag,
    description: "Lập lịch Race: tạo, lên lịch, quản lý status.",
  },
  {
    title: "Referee Assignment",
    href: "/admin/referee-assignments",
    role: "Admin",
    icon: Award,
    description: "Phân công trọng tài: assign referee cho từng race.",
  },
  {
    title: "Ranking Management",
    href: "/admin/rankings",
    role: "Admin",
    icon: Medal,
    description: "Xem/cập nhật ranking ngựa và jockey theo giải.",
  },
  {
    title: "Prize Management",
    href: "/admin/prizes",
    role: "Admin",
    icon: Trophy,
    description: "Quản lý giải thưởng: xem, cập nhật trạng thái payment.",
  },
  {
    title: "Bet Management",
    href: "/admin/bets",
    role: "Admin",
    icon: Activity,
    description: "Quản lý dự đoán: xem tất cả bets của hệ thống.",
  },
  {
    title: "Wallet Transactions",
    href: "/admin/wallet",
    role: "Admin",
    icon: Wallet,
    description: "Quản lý giao dịch điểm: nạp tiền, cashout queue.",
  },
  {
    title: "Results",
    href: "/admin/results",
    role: "Admin",
    icon: ListChecks,
    description: "Per-race result review and publish queue.",
  },
  {
    title: "Audit Logs",
    href: "/admin/audit-logs",
    role: "Admin",
    icon: FileText,
    description: "View system operations and secure transaction trails.",
  },
  {
    title: "Trạm Điều Hành",
    href: "/owner",
    role: "Owner",
    icon: Home,
    description: "Stable shell for horses, registration, jockey handoff.",
  },
  {
    title: "Chuồng Chiến Mã",
    href: "/owner/horses",
    role: "Owner",
    icon: ShieldCheck,
    description: "Manage your horse stable, health status and details.",
  },
  {
    title: "Đăng Ký Trận Đua",
    href: "/owner/races",
    role: "Owner",
    icon: Flag,
    description: "Browse open races and enroll your healthy horses.",
  },
  {
    title: "Lịch Sử Ghi Danh",
    href: "/owner/registrations",
    role: "Owner",
    icon: ClipboardCheck,
    description: "Track approval progress of your horse race registrations.",
  },
  {
    title: "Mời Jockey",
    href: "/owner/jockey-invitations",
    role: "Owner",
    icon: Users,
    description: "Invite professional jockeys for your approved horses.",
  },
  {
    title: "Ví Của Tôi",
    href: "/owner/wallet",
    role: "Owner",
    icon: Wallet,
    description: "View rewards ledger, split earnings, and request cashouts.",
  },
  {
    title: "Trạm Điều Hành",
    href: "/jockey",
    role: "Jockey",
    icon: Gauge,
    description: "Bảng điều khiển tổng hợp, lịch đua, lời mời mới và kết quả gần đây.",
  },
  {
    title: "Lời Mời Cưỡi Ngựa",
    href: "/jockey?tab=invitations",
    role: "Jockey",
    icon: Users,
    description: "Tiếp nhận và phản hồi lời mời thi đấu từ các chủ ngựa.",
  },
  {
    title: "Lịch Thi Đấu Đã Nhận",
    href: "/jockey?tab=assigned",
    role: "Jockey",
    icon: Flag,
    description: "Xem chi tiết lịch đua đã nhận lời và thông tin chiến mã.",
  },
  {
    title: "Thông Tin Chiến Mã",
    href: "/jockey?tab=horses",
    role: "Jockey",
    icon: ShieldCheck,
    description: "Xem chi tiết chỉ số sức mạnh, sức bền và thể trạng các ngựa điều khiển.",
  },
  {
    title: "Thành Tích Cá Nhân",
    href: "/jockey?tab=performance",
    role: "Jockey",
    icon: Award,
    description: "Xem chi tiết chỉ số kỹ năng nghề nghiệp và kết quả sự nghiệp.",
  },
  {
    title: "Ví Của Tôi",
    href: "/jockey/wallet",
    role: "Jockey",
    icon: Wallet,
    description: "Xem điểm thưởng chia tỷ lệ 30% và lịch sử cashout.",
  },
  {
    title: "Trạm Điều Hành",
    href: "/referee",
    role: "Referee",
    icon: Home,
    description: "Bảng điều khiển giám sát tổng hợp của Trọng tài.",
  },
  {
    title: "Race Được Phân Công",
    href: "/referee/assignments",
    role: "Referee",
    icon: Flag,
    description: "Danh sách các cuộc đua được phân công giám sát và điều hành.",
  },
  {
    title: "Pre-race Check",
    href: "/referee/pre-race",
    role: "Referee",
    icon: ShieldCheck,
    description: "Kiểm tra sức khỏe ngựa và điểm danh nài ngựa trước Race.",
  },
  {
    title: "Theo Dõi Race",
    href: "/referee/monitoring",
    role: "Referee",
    icon: Activity,
    description: "Theo dõi trạng thái xuất phát và trực tiếp của cuộc đua.",
  },
  {
    title: "Xác Nhận Kết Quả",
    href: "/referee/result-entry",
    role: "Referee",
    icon: Award,
    description: "Nhập thời gian về đích chính thức và xếp hạng chiến mã.",
  },
  {
    title: "Ghi Nhận Vi Phạm",
    href: "/referee/violations",
    role: "Referee",
    icon: Siren,
    description: "Báo cáo lỗi vi phạm và tự động áp dụng giây phạt kỷ luật.",
  },
  {
    title: "Biên Bản Thi Đấu",
    href: "/referee/reports",
    role: "Referee",
    icon: FileText,
    description: "Quản lý và lập biên bản thi đấu chính thức cho các cuộc đua.",
  },
  {
    title: "Giải Đấu Nổi Bật",
    href: "/spectator",
    role: "Spectator",
    icon: Trophy,
    description: "Danh sách giải đấu nổi bật đang diễn ra và sắp khởi tranh.",
  },
  {
    title: "Thông Tin Giải Đấu",
    href: "/spectator/tournaments",
    role: "Spectator",
    icon: ListChecks,
    description: "Thông tin chi tiết, điều lệ và cơ cấu giải thưởng giải đấu.",
  },
  {
    title: "Lịch Thi Đấu",
    href: "/spectator/races",
    role: "Spectator",
    icon: Flag,
    description: "Lịch đua, sơ đồ đường chạy và thời gian xuất phát chi tiết.",
  },
  {
    title: "Kết Quả Trực Tiếp",
    href: "/spectator/results",
    role: "Spectator",
    icon: Activity,
    description: "Xem trực tiếp kết quả và trạng thái về đích của các chú ngựa.",
  },
  {
    title: "Bảng Xếp Hạng",
    href: "/spectator/rankings",
    role: "Spectator",
    icon: Medal,
    description: "Bảng xếp hạng thành tích chiến mã và nài ngựa xuất sắc nhất.",
  },
  {
    title: "Ví Điểm Thưởng",
    href: "/spectator/wallet",
    role: "Spectator",
    icon: Wallet,
    description: "Ví điểm dự đoán, lịch sử quy đổi và mã nhận thưởng tại quầy.",
  },
  {
    title: "Dự Đoán Kết Quả",
    href: "/spectator/predictions",
    role: "Spectator",
    icon: Bell,
    description: "Tham gia dự đoán ngựa vô địch nhận điểm thưởng miễn phí.",
  },
  // ─── COUNTER STAFF ──────────────────────────────────────────────────
  {
    title: "Bàn Làm Việc",
    href: "/counter-staff",
    role: "CounterStaff",
    icon: Gauge,
    description: "Tổng quan quầy giao dịch, tra cứu nhanh thông tin và thống kê.",
  },
  {
    title: "Đổi Thưởng Vật Lý",
    href: "/counter-staff/redemptions",
    role: "CounterStaff",
    icon: Gift,
    description: "Xử lý hàng đợi đổi quà, phê duyệt và xác nhận trao quà vật lý.",
  },
  {
    title: "Nạp Tiền Vào Ví",
    href: "/counter-staff/deposit",
    role: "CounterStaff",
    icon: Wallet,
    description: "Nạp tiền/điểm trực tiếp vào tài khoản ví của người dùng.",
  },
];
