import {
  Activity,
  AlertTriangle,
  Award,
  Bell,
  ClipboardCheck,
  FileText,
  Flag,
  Gauge,
  Home,
  ListChecks,
  PlusCircle,
  ShieldCheck,
  Siren,
  Trophy,
  Users,
  Wallet,
} from "lucide-react";

import type { NavigationItem } from "@/types/navigation";

export const publicNavigation: NavigationItem[] = [
  { title: "Home", href: "/", icon: Home },
  { title: "Tournaments", href: "/tournaments", icon: Trophy },
  { title: "Races", href: "/races", icon: Flag },
  { title: "Rankings", href: "#", icon: Gauge },
  { title: "Predictions", href: "#", icon: Bell },
  { title: "News", href: "#", icon: ClipboardCheck },
  { title: "Contact", href: "/#contact", icon: Users },
];

export const dashboardNavigation: NavigationItem[] = [
  {
    title: "Admin home",
    href: "/admin",
    role: "Admin",
    icon: Gauge,
    description:
      "Race control shell for tournaments, races, registrations, results.",
  },
  {
    title: "Create tournament",
    href: "/admin/tournaments/new",
    role: "Admin",
    icon: PlusCircle,
    description: "Future entry for tournament container creation.",
  },
  {
    title: "Create race",
    href: "/admin/races/new",
    role: "Admin",
    icon: Flag,
    description: "Future entry for independent race scheduling.",
  },
  {
    title: "Registrations",
    href: "/admin/registrations",
    role: "Admin",
    icon: ClipboardCheck,
    description: "Horse registration moderation queue.",
  },
  {
    title: "Results",
    href: "/admin/results",
    role: "Admin",
    icon: ListChecks,
    description: "Per-race result review and publish queue.",
  },
  {
    title: "Cashout Queue",
    href: "/admin/cashouts",
    role: "Admin",
    icon: Wallet,
    description: "Process points redemption requests for Owners and Jockeys.",
  },
  {
    title: "Audit Logs",
    href: "/admin/audit-logs",
    role: "Admin",
    icon: FileText,
    description: "View system operations and secure transactions trails.",
  },
  {
    title: "Trạm Điều Hành",
    href: "/owner",
    role: "Owner",
    icon: Home,
    description: "Stable shell for horses, registration, jockey handoff.",
  },
  {
    title: "Chuồng Chiến Mã",
    href: "/owner/horses",
    role: "Owner",
    icon: ShieldCheck,
    description: "Manage your horse stable, health status and details.",
  },
  {
    title: "Đăng Ký Trận Đua",
    href: "/owner/races",
    role: "Owner",
    icon: Flag,
    description: "Browse open races and enroll your healthy horses.",
  },
  {
    title: "Lịch Sử Ghi Danh",
    href: "/owner/registrations",
    role: "Owner",
    icon: ClipboardCheck,
    description: "Track approval progress of your horse race registrations.",
  },
  {
    title: "Mời Jockey",
    href: "/owner/jockey-invitations",
    role: "Owner",
    icon: Users,
    description: "Invite professional jockeys for your approved horses.",
  },
  {
    title: "Ví Của Tôi",
    href: "/owner/wallet",
    role: "Owner",
    icon: Wallet,
    description: "View rewards ledger, split earnings, and request cashouts.",
  },
  {
    title: "Trạm Điều Hành",
    href: "/jockey",
    role: "Jockey",
    icon: Gauge,
    description: "Bảng điều khiển tổng hợp, lịch đua, lời mời mới và kết quả gần đây.",
  },
  {
    title: "Lời Mời Cưỡi Ngựa",
    href: "/jockey?tab=invitations",
    role: "Jockey",
    icon: Users,
    description: "Tiếp nhận và phản hồi lời mời thi đấu từ các chủ ngựa.",
  },
  {
    title: "Lịch Thi Đấu Đã Nhận",
    href: "/jockey?tab=assigned",
    role: "Jockey",
    icon: Flag,
    description: "Xem chi tiết lịch đua đã nhận lời và thông tin chiến mã.",
  },
  {
    title: "Thông Tin Chiến Mã",
    href: "/jockey?tab=horses",
    role: "Jockey",
    icon: ShieldCheck,
    description: "Xem chi tiết chỉ số sức mạnh, sức bền và thể trạng các ngựa điều khiển.",
  },
  {
    title: "Thành Tích Cá Nhân",
    href: "/jockey?tab=performance",
    role: "Jockey",
    icon: Award,
    description: "Xem chi tiết chỉ số kỹ năng nghề nghiệp và kết quả sự nghiệp.",
  },
  {
    title: "Ví Của Tôi",
    href: "/jockey/wallet",
    role: "Jockey",
    icon: Wallet,
    description: "Xem điểm thưởng chia tỷ lệ 30% và lịch sử cashout.",
  },
  {
    title: "Trạm Điều Hành",
    href: "/referee",
    role: "Referee",
    icon: Home,
    description: "Bảng điều khiển giám sát tổng hợp của Trọng tài.",
  },
  {
    title: "Race Được Phân Công",
    href: "/referee/assignments",
    role: "Referee",
    icon: Flag,
    description: "Danh sách các cuộc đua được phân công giám sát và điều hành.",
  },
  {
    title: "Pre-race Check",
    href: "/referee/pre-race",
    role: "Referee",
    icon: ShieldCheck,
    description: "Kiểm tra sức khỏe ngựa và điểm danh nài ngựa trước Race.",
  },
  {
    title: "Theo Dõi Race",
    href: "/referee/monitoring",
    role: "Referee",
    icon: Activity,
    description: "Theo dõi trạng thái xuất phát và trực tiếp của cuộc đua.",
  },
  {
    title: "Xác Nhận Kết Quả",
    href: "/referee/result-entry",
    role: "Referee",
    icon: Award,
    description: "Nhập thời gian về đích chính thức và xếp hạng chiến mã.",
  },
  {
    title: "Ghi Nhận Vi Phạm",
    href: "/referee/violations",
    role: "Referee",
    icon: Siren,
    description: "Báo cáo lỗi vi phạm và tự động áp dụng giây phạt kỷ luật.",
  },
  {
    title: "Biên Bản Thi Đấu",
    href: "/referee/reports",
    role: "Referee",
    icon: FileText,
    description: "Quản lý và lập biên bản thi đấu chính thức cho các cuộc đua.",
  },
  {
    title: "Spectator home",
    href: "/spectator",
    role: "Spectator",
    icon: Bell,
    description: "Race view, prediction, notification shell.",
  },
  {
    title: "My Wallet",
    href: "/spectator/wallet",
    role: "Spectator",
    icon: Wallet,
    description: "Xem điểm thưởng free tích lũy từ dự đoán và đổi thưởng tại quầy.",
  },
];
